# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/master/c2cciutils/schema.json

checks:
  codespell:
    arguments:
      - --quiet-level=2
      - --check-filenames
      - --ignore-words-list=nd

publish:
  docker:
    images:
      - name: camptocamp/jsonschema-gentypes

audit:
  snyk:
    pip_install_arguments:
      - --user
      - --ignore-installed
